### ISSUE TITLE
Query "Get Report"

### ISSUE THREAD

**Issue by andreas0087** [alextoft/sureflap#11]
Is it possible to provide a query to get the reports.  That would be very great!

![2019-05-23_235816](https://user-images.githubusercontent.com/50969483/58289395-904d0f80-7db6-11e9-8489-a10f58015cb6.jpg)

**Comment by hdurdle** [comment]
Everything you need is exposed in the API on the surepetcare.io site.  In this case you need to query:
`https://app.api.surehub.io/api/pet/<your pet ID>/position/summary/v2?from=2018-11-24&to=2019-05-24` put your pet ID and the dates you want, you'll get back a json object with dates and movements. 

You should be able to adapt any of the examples already in the repository to do this.

**Comment by andreas0087** [comment]
Hi "hdurdle",

thank you very much for your support! I used this query and got a list of all movements. Thanks!

I've one more question:

Is there's a way (query) to remove a movement from the surepetcare database? Or do change it?

**Comment by hdurdle** [comment]
If there is, I haven't seen it exposed in any of their UI.  The fact that the mechanism to get a movement is to retrieve a whole group of them from a /summary endpoint, and not a /movement endpoint would indicate it doesn't exist as a discrete object you can query.

**Comment by andreas0087** [comment]
Ok I understand.
Trank you very much for your Support.
